/*
author:wuzheng
* time:2025/8/7
* log:完成，可修改730x336
 */
export const swiperList:string[]=[
  "https://tse4-mm.cn.bing.net/th/id/OIP-C.vy0o5qk9rSFDqF5ju7lUjAHaDa?w=208&h=96&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  "https://ts1.tc.mm.bing.net/th/id/R-C.377e4074ccb42bd875abb3b24c962306?rik=dT3WuwgQEi83Hg&riu=http%3a%2f%2fp1.music.126.net%2fhj9mjqAfZl8Vs-FFKqF7sw%3d%3d%2f109951163679717523.jpg&ehk=8yN%2fgvW5pqZWYzjGLEaa5EOyLEziCGu5pgLSuYjFv1A%3d&risl=&pid=ImgRaw&r=0",
  "https://ts1.tc.mm.bing.net/th/id/R-C.71e35c23651360a51acc66690dd90228?rik=g4yNGpIwKGSevA&riu=http%3a%2f%2fp1.music.126.net%2flFclrYWv39qwhivuMObqsA%3d%3d%2f109951163592885724.jpg&ehk=PYeVMaX67oahvF2AcpLorRynZNReiQGzNfHgVbqbMzM%3d&risl=&pid=ImgRaw&r=0"
]//轮播图数据